[package]
name = "dotium"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0"
age = "0"
chrono = "0"
clap = { version = "3", features = ["cargo", "derive"] }
diff = "0"
env_logger = "0"
log = "0"
tera = "1"
toml = "0"
